# Generated by Django 4.0.2 on 2022-02-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('base_discount', models.DecimalField(decimal_places=2, max_digits=99, verbose_name='Descuento base del servicio')),
                ('identifier_name', models.CharField(max_length=100, verbose_name='Identificador del servicio (Número, Cuenta, etc)')),
                ('identifier_length', models.IntegerField(verbose_name='Longitud del identificador')),
                ('additional_identifier', models.JSONField(verbose_name='Identificadores adicionales')),
                ('service_type', models.ManyToManyField(to='services.ServiceType')),
            ],
        ),
    ]
