# Generated by Django 4.0.2 on 2022-02-19 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('whatsapp_number', models.CharField(max_length=15, verbose_name='Whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorServicePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Monto del pago')),
                ('discount', models.FloatField(verbose_name='Descuento del pago')),
                ('collaborator', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('customer', models.ManyToManyField(to='collaborator.Customer')),
                ('service', models.ManyToManyField(to='services.Service')),
            ],
        ),
    ]
